# Generated by Django 5.2.17 on 2026-08-21 20:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('HUMAN', 'Human assessment'), ('AI', 'AI assessment'), ('CONSENSUS', 'Consensus assessment'), ('SCENARIO', 'Scenario assessment')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('project__code', 'kind', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('PROJECT', 'Project'), ('TIME_SLICE', 'Time slice'), ('TENSION_POINT', 'Tension point'), ('PARTICIPANT_GROUP', 'Participant group'), ('GROUP_TENSION_RELATION', 'Group-tension relation')], max_length=32)),
                ('value_type', models.CharField(choices=[('DECIMAL', 'Decimal'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('TEXT', 'Text'), ('JSON', 'JSON')], default='DECIMAL', max_length=16)),
                ('scale_min', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('scale_max', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('scale_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('project__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_project_code_not_empty'), models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_project_version_not_empty'), models.UniqueConstraint(fields=('code',), name='domain_project_code_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('definition', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_groups', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('PROJECT', 'Project'), ('TIME_SLICE', 'Time slice'), ('TENSION_POINT', 'Tension point'), ('PARTICIPANT_GROUP', 'Participant group'), ('GROUP_TENSION_RELATION', 'Group-tension relation')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not applicable'), ('INSUFFICIENT_DATA', 'Insufficient data'), ('PROVISIONAL', 'Provisional'), ('CONFIRMED', 'Confirmed'), ('OPEN_METHOD', 'Method not yet approved')], default='UNKNOWN', max_length=32)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('note', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('range_min', models.JSONField(blank=True, default=None, null=True)),
                ('range_max', models.JSONField(blank=True, default=None, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('assessment_set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameter_values', to='domain.assessmentset')),
                ('parameter_definition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='values', to='domain.parameterdefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'time_slice__order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='parameterdefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_definitions', to='domain.project'),
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('additional_urls', models.JSONField(blank=True, default=list)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('accessed_on', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('SUPPORTS', 'Supports'), ('CONTRADICTS', 'Contradicts'), ('CONTEXT', 'Context')], default='SUPPORTS', max_length=16)),
                ('rationale', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='value_links', to='domain.evidencesource')),
                ('parameter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='domain.parametervalue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'parameter_value__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='CalculationStrategyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=16)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_strategies', to='domain.project')),
            ],
            options={
                'ordering': ('code', 'version'),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock')], max_length=16)),
                ('actor_type', models.CharField(choices=[('HUMAN', 'Human'), ('AI', 'AI'), ('SYSTEM', 'System')], max_length=16)),
                ('actor_identifier', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=128)),
                ('entity_id', models.UUIDField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assessment_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='domain.assessmentset')),
                ('parameter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='domain.parametervalue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='domain.project')),
            ],
            options={
                'ordering': ('-occurred_at', 'code'),
            },
        ),
        migrations.AddField(
            model_name='assessmentset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sets', to='domain.project'),
        ),
        migrations.CreateModel(
            name='ProjectLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_structure_locked', models.BooleanField(default=False)),
                ('ordinary_user_can_edit_structure', models.BooleanField(default=True)),
                ('studio_can_edit_structure', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_lock', to='domain.project')),
            ],
            options={
                'ordering': ('project__code',),
            },
        ),
        migrations.CreateModel(
            name='ProjectSchemaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=False)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('manifest_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='A manifest hash must be a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_versions', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('assessment_set', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='scenario', to='domain.assessmentset')),
                ('base_assessment_set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='derived_scenarios', to='domain.assessmentset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('PROJECT', 'Project'), ('TIME_SLICE', 'Time slice'), ('TENSION_POINT', 'Tension point'), ('PARTICIPANT_GROUP', 'Participant group'), ('GROUP_TENSION_RELATION', 'Group-tension relation')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not applicable'), ('INSUFFICIENT_DATA', 'Insufficient data'), ('PROVISIONAL', 'Provisional'), ('CONFIRMED', 'Confirmed'), ('OPEN_METHOD', 'Method not yet approved')], default='UNKNOWN', max_length=32)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('note', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('range_min', models.JSONField(blank=True, default=None, null=True)),
                ('range_max', models.JSONField(blank=True, default=None, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('parameter_definition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scenario_overrides', to='domain.parameterdefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_overrides', to='domain.project')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='domain.scenario')),
            ],
            options={
                'ordering': ('project__code', 'scenario__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='TensionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('definition', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tension_points', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='GroupTensionRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tension_relations', to='domain.participantgroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tension_relations', to='domain.project')),
                ('tension_point', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_relations', to='domain.tensionpoint')),
            ],
            options={
                'ordering': ('project__code', 'participant_group__order', 'tension_point__order'),
            },
        ),
        migrations.CreateModel(
            name='TimeSlice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('cutoff_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slices', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'order', 'cutoff_date'),
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='time_slice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scenarios', to='domain.timeslice'),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='time_slice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameter_values', to='domain.timeslice'),
        ),
        migrations.AddConstraint(
            model_name='participantgroup',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_participant_group_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='participantgroup',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_participant_group_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='participantgroup',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_group_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='participantgroup',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='domain_group_project_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_parameter_def_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_parameter_def_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_parameter_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('scale_min__isnull', True), ('scale_max__isnull', True), ('scale_min__lte', models.F('scale_max')), _connector='OR'), name='domain_parameter_scale_order'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_evidence_source_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_evidence_source_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_source_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.CheckConstraint(condition=models.Q(('published_on__isnull', True), ('accessed_on__isnull', True), ('accessed_on__gte', models.F('published_on')), _connector='OR'), name='domain_source_access_after_publish'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_evidence_link_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_evidence_link_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_link_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.UniqueConstraint(fields=('parameter_value', 'source'), name='domain_link_value_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='calculationstrategydefinition',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_strategy_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='calculationstrategydefinition',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_strategy_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='calculationstrategydefinition',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='domain_strategy_code_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['project', 'entity_type', 'entity_id'], name='domain_audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['project', 'occurred_at'], name='domain_audit_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_audit_event_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_audit_event_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_audit_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assessmentset',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_assessment_set_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='assessmentset',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_assessment_set_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='assessmentset',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_set_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectlock',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_project_lock_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='projectlock',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_project_lock_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='projectlock',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_lock_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectlock',
            constraint=models.CheckConstraint(condition=models.Q(('is_structure_locked', False), ('ordinary_user_can_edit_structure', False), _connector='OR'), name='domain_lock_blocks_ordinary'),
        ),
        migrations.AddConstraint(
            model_name='projectschemaversion',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_schema_version_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='projectschemaversion',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_schema_version_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='projectschemaversion',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_schema_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectschemaversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='domain_schema_project_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectschemaversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='domain_schema_one_current'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_scenario_override_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_scenario_override_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_override_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.UniqueConstraint(fields=('scenario', 'parameter_definition', 'target_type', 'target_id'), name='domain_override_context_target_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD')), ('value__isnull', True)), models.Q(('status__in', ('PROVISIONAL', 'CONFIRMED')), ('value__isnull', False)), _connector='OR'), name='domain_override_status_value_consistent'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence__isnull', True), ('range_max__isnull', True), ('range_min__isnull', True), ('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD'))), models.Q(('confidence__isnull', False), ('status__in', ('PROVISIONAL', 'CONFIRMED')), models.Q(('rationale', ''), _negated=True), models.Q(models.Q(('range_max__isnull', True), ('range_min__isnull', True)), models.Q(('range_max__isnull', False), ('range_min__isnull', False)), _connector='OR')), _connector='OR'), name='domain_override_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='tensionpoint',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_tension_point_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tensionpoint',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_tension_point_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tensionpoint',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_tension_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tensionpoint',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='domain_tension_project_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='grouptensionrelation',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_group_tension_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='grouptensionrelation',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_group_tension_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='grouptensionrelation',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_relation_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='grouptensionrelation',
            constraint=models.UniqueConstraint(fields=('project', 'participant_group', 'tension_point'), name='domain_relation_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timeslice',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_time_slice_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='timeslice',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_time_slice_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='timeslice',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_slice_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timeslice',
            constraint=models.UniqueConstraint(fields=('project', 'cutoff_date'), name='domain_slice_project_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_scenario_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_scenario_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_scenario_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('assessment_set', models.F('base_assessment_set')), _negated=True), name='domain_scenario_distinct_sets'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_parameter_value_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_parameter_value_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='domain_value_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('project', 'time_slice', 'assessment_set', 'parameter_definition', 'target_type', 'target_id'), name='domain_value_context_target_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD')), ('value__isnull', True)), models.Q(('status__in', ('PROVISIONAL', 'CONFIRMED')), ('value__isnull', False)), _connector='OR'), name='domain_value_status_value_consistent'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence__isnull', True), ('range_max__isnull', True), ('range_min__isnull', True), ('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD'))), models.Q(('confidence__isnull', False), ('status__in', ('PROVISIONAL', 'CONFIRMED')), models.Q(('rationale', ''), _negated=True), models.Q(models.Q(('range_max__isnull', True), ('range_min__isnull', True)), models.Q(('range_max__isnull', False), ('range_min__isnull', False)), _connector='OR')), _connector='OR'), name='domain_value_metadata_consistent'),
        ),
    ]
