# Generated by Django 5.2.17 on 2026-08-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_foundation_v4_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sets', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='timeslice',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slices', to='domain.projectworkspace'),
        ),
    ]
