# Generated by Django 5.2.17 on 2026-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_foundation_v4_workspace_required'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='powercomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence__isnull', True), ('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD'))), models.Q(('confidence__isnull', False), ('status__in', ('PROVISIONAL', 'CONFIRMED', 'DISPUTED', 'RETROSPECTIVE_KNOWLEDGE')), models.Q(('rationale', ''), _negated=True)), _connector='OR'), name='domain_power_metadata_state'),
        ),
    ]
