# Generated by Django 5.2.17 on 2026-08-24 10:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_power_metadata_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyTermMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_code', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('legacy_label', models.CharField(blank=True, max_length=500)),
                ('source_version', models.CharField(max_length=64)),
                ('mapping_status', models.CharField(choices=[('RENAME_ONLY', 'Rename only'), ('TRANSFER_WITH_REVIEW', 'Transfer with review'), ('METHOD_BLOCKED', 'Method blocked'), ('RECODING_REQUIRED', 'Recoding required')], max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('workspace__code', 'legacy_code', 'source_version'),
            },
        ),
        migrations.CreateModel(
            name='TerminologyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_ru_name', models.CharField(max_length=500)),
                ('canonical_ru_acronym', models.CharField(blank=True, max_length=64)),
                ('exact_en_term', models.CharField(max_length=500)),
                ('exact_en_acronym', models.CharField(blank=True, max_length=64)),
                ('source_framework', models.CharField(max_length=500)),
                ('source_citation', models.TextField()),
                ('construct_version', models.CharField(max_length=64)),
                ('locale', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Locale must be a BCP-47 language tag such as en or ru-RU.', regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('display_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('workspace__code', 'code', 'construct_version', 'locale'),
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('domain.chatconversation',),
        ),
        migrations.RemoveConstraint(
            model_name='actorelementassessment',
            name='domain_actor_assessment_context_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='chatcitation',
            name='domain_chat_citation_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='parametervalue',
            name='domain_value_context_target_uniq',
        ),
        migrations.AddField(
            model_name='actorelementassessment',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='successor', to='domain.actorelementassessment'),
        ),
        migrations.AddField(
            model_name='chatcitation',
            name='quote_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatcitation',
            name='quote_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatcitation',
            name='quote_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='channel_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('PROJECT_SHARED', 'Project shared')], default='PERSONAL', max_length=24),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='owner_identifier',
            field=models.CharField(default='UNSPECIFIED', max_length=255),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='COMPLETE', max_length=16),
        ),
        migrations.AddField(
            model_name='fact',
            name='coder_identifier',
            field=models.CharField(default='UNSPECIFIED', max_length=255),
        ),
        migrations.AddField(
            model_name='fact',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='fact',
            name='temporal_status',
            field=models.CharField(choices=[('CONTEMPORANEOUS', 'Contemporaneous'), ('RETROSPECTIVE_KNOWLEDGE', 'Retrospective knowledge'), ('RETROSPECTIVE_CORROBORATION', 'Retrospective corroboration'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=40),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='successor', to='domain.parametervalue'),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='temporal_status',
            field=models.CharField(choices=[('CONTEMPORANEOUS', 'Contemporaneous'), ('RETROSPECTIVE_KNOWLEDGE', 'Retrospective knowledge'), ('NO_DIRECT_POSITION', 'No direct position'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=40),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='construct_version',
            field=models.CharField(default='1.0.0', max_length=64),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='published_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='schema_version',
            field=models.CharField(default='1.0.0', max_length=64),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='semantic_version',
            field=models.CharField(default='1.0.0', max_length=64),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='validated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectdefinitionversion',
            name='validation_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectpublication',
            name='actor_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectpublication',
            name='validation_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('VALIDATE', 'Validate'), ('PUBLISH', 'Publish'), ('FREEZE', 'Freeze'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='actorelementassessment',
            constraint=models.UniqueConstraint(fields=('workspace', 'actor', 'element', 'time_slice', 'assessment_set', 'version'), name='domain_actor_assessment_context_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chatcitation',
            constraint=models.CheckConstraint(condition=models.Q(('document_version__isnull', False), ('fragment__isnull', False), ('quote_end__isnull', False), ('quote_start__isnull', False), models.Q(('quote_text', ''), _negated=True), ('quote_end__gt', models.F('quote_start'))), name='domain_chat_citation_exact_span'),
        ),
        migrations.AddConstraint(
            model_name='chatconversation',
            constraint=models.CheckConstraint(condition=models.Q(('owner_identifier', ''), _negated=True), name='domain_chat_owner_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ERROR'), models.Q(('error', ''), _negated=True)), models.Q(('error', ''), ('status', 'COMPLETE')), _connector='OR'), name='domain_chat_message_status_error'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('coder_identifier', ''), _negated=True), name='domain_fact_coder_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 100)), _connector='OR'), name='domain_fact_confidence_0_100'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('workspace', 'time_slice', 'assessment_set', 'parameter_definition', 'target_type', 'target_id', 'version'), name='domain_value_context_target_version_uniq'),
        ),
        migrations.AddField(
            model_name='legacytermmapping',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_term_mappings', to='domain.projectworkspace'),
        ),
        migrations.AddField(
            model_name='terminologyentry',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminology_entries', to='domain.projectworkspace'),
        ),
        migrations.AddField(
            model_name='legacytermmapping',
            name='terminology_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='legacy_mappings', to='domain.terminologyentry'),
        ),
        migrations.AddConstraint(
            model_name='terminologyentry',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_term_entry_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='terminologyentry',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_term_entry_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='terminologyentry',
            constraint=models.UniqueConstraint(fields=('workspace', 'code', 'construct_version', 'locale'), name='domain_term_entry_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='terminologyentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canonical_ru_name', ''), _negated=True), models.Q(('exact_en_term', ''), _negated=True), models.Q(('source_framework', ''), _negated=True), models.Q(('source_citation', ''), _negated=True), models.Q(('construct_version', ''), _negated=True)), name='domain_term_entry_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='legacytermmapping',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_legacy_term_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='legacytermmapping',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_legacy_term_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='legacytermmapping',
            constraint=models.UniqueConstraint(fields=('workspace', 'legacy_code', 'source_version'), name='domain_legacy_term_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legacytermmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mapping_status', 'RENAME_ONLY'), ('terminology_entry__isnull', False)), models.Q(('mapping_status', 'TRANSFER_WITH_REVIEW'), ('terminology_entry__isnull', False)), ('mapping_status__in', ('METHOD_BLOCKED', 'RECODING_REQUIRED')), _connector='OR'), name='domain_legacy_term_target_state'),
        ),
    ]
