# Generated by Django 5.2.17 on 2026-08-24 10:52

from django.db import migrations, models


MIGRATION_ACTOR = "MIGRATION-CA-SUITE-I1-FOUNDATION-001"


def backfill_definition_lifecycle(apps, schema_editor):
    ProjectDefinitionVersion = apps.get_model("domain", "ProjectDefinitionVersion")
    ProjectPublication = apps.get_model("domain", "ProjectPublication")

    for definition in ProjectDefinitionVersion.objects.filter(
        publication_status__in=("PUBLISHED", "RETIRED")
    ).iterator():
        lifecycle_time = definition.published_at or definition.updated_at
        definition.validated_at = definition.validated_at or lifecycle_time
        definition.validated_by = definition.validated_by or MIGRATION_ACTOR
        if definition.validation_result.get("valid") is not True:
            definition.validation_result = {
                "valid": True,
                "source": "PR21_UPGRADE_COMPATIBILITY",
            }
        definition.published_at = definition.published_at or lifecycle_time
        definition.published_by = definition.published_by or MIGRATION_ACTOR
        definition.save(
            update_fields=(
                "validated_at",
                "validated_by",
                "validation_result",
                "published_at",
                "published_by",
            )
        )

    for publication in ProjectPublication.objects.all().iterator():
        publication.actor_identifier = publication.actor_identifier or MIGRATION_ACTOR
        if publication.validation_result.get("valid") is not True:
            publication.validation_result = {
                "valid": True,
                "source": "PR21_UPGRADE_COMPATIBILITY",
            }
        publication.save(update_fields=("actor_identifier", "validation_result"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_foundation_contract_completion'),
    ]

    operations = [
        migrations.RunPython(backfill_definition_lifecycle, noop_reverse),
        migrations.AddConstraint(
            model_name='projectdefinitionversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'DRAFT'), ('published_at__isnull', True), ('published_by', ''), ('validated_at__isnull', True), ('validated_by', ''), ('validation_result', {})), models.Q(('publication_status', 'VALIDATED'), ('published_at__isnull', True), ('published_by', ''), ('validated_at__isnull', False), ('validation_result__valid', True), models.Q(('validated_by', ''), _negated=True)), models.Q(('publication_status__in', ('PUBLISHED', 'RETIRED')), ('published_at__isnull', False), ('validated_at__isnull', False), ('validation_result__valid', True), models.Q(('validated_by', ''), _negated=True), models.Q(('published_by', ''), _negated=True)), _connector='OR'), name='domain_definition_lifecycle_state'),
        ),
        migrations.AddConstraint(
            model_name='projectpublication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_identifier', ''), _negated=True), ('validation_result__valid', True)), name='domain_publication_actor_validation'),
        ),
    ]
