# Generated by Django 5.2.17 on 2026-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_definition_lifecycle_enforcement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parametervalue',
            name='domain_value_metadata_consistent',
        ),
        migrations.RemoveConstraint(
            model_name='scenariooverride',
            name='domain_override_metadata_consistent',
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence__isnull', True), ('range_max__isnull', True), ('range_min__isnull', True), ('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD'))), models.Q(('status__in', ('PROVISIONAL', 'CONFIRMED', 'DISPUTED', 'RETROSPECTIVE_KNOWLEDGE')), models.Q(models.Q(('confidence__isnull', False), models.Q(('rationale', ''), _negated=True)), ('actor_element_assessment__isnull', False), _connector='OR'), models.Q(models.Q(('range_max__isnull', True), ('range_min__isnull', True)), models.Q(('range_max__isnull', False), ('range_min__isnull', False)), _connector='OR')), _connector='OR'), name='domain_value_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='scenariooverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence__isnull', True), ('range_max__isnull', True), ('range_min__isnull', True), ('status__in', ('UNKNOWN', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA', 'OPEN_METHOD'))), models.Q(('status__in', ('PROVISIONAL', 'CONFIRMED', 'DISPUTED', 'RETROSPECTIVE_KNOWLEDGE')), ('confidence__isnull', False), models.Q(('rationale', ''), _negated=True), models.Q(models.Q(('range_max__isnull', True), ('range_min__isnull', True)), models.Q(('range_max__isnull', False), ('range_min__isnull', False)), _connector='OR')), _connector='OR'), name='domain_override_metadata_consistent'),
        ),
    ]
