# Generated by Django 5.2.17 on 2026-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_assessment_header_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factevidence',
            name='relation',
            field=models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('CONTEXT', 'Context'), ('CHALLENGES', 'Challenges'), ('CONTEXTUALIZES', 'Contextualizes')], default='SUPPORTS', max_length=16),
        ),
    ]
