# Generated by Django 5.2.17 on 2026-08-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_evidence_relation_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentevidence',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidence_links', to='domain.actorelementassessment'),
        ),
        migrations.AlterField(
            model_name='assessmentevidence',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_evidence_links', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='assessment_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='domain.assessmentset'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='parameter_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='domain.parametervalue'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='domain.project'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='chatcitation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citations', to='domain.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatcitation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chat_citations', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='domain.chatconversation'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chat_messages', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_contents', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_versions', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facts', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='factevidence',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidence_links', to='domain.fact'),
        ),
        migrations.AlterField(
            model_name='factevidence',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fact_evidence_links', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='import_runs', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='legacycompatibilityreceipt',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='legacy_compatibility_receipts', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='legacytermmapping',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='legacy_term_mappings', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='parametervalueevidence',
            name='parameter_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fact_evidence_links', to='domain.parametervalue'),
        ),
        migrations.AlterField(
            model_name='parametervalueevidence',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameter_value_evidence_links', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='powercomponentevidence',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidence_links', to='domain.powercomponent'),
        ),
        migrations.AlterField(
            model_name='powercomponentevidence',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='power_evidence_links', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='terminologyentry',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='terminology_entries', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='textfragment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='text_fragments', to='domain.projectworkspace'),
        ),
        migrations.AlterField(
            model_name='uihelpbinding',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='help_bindings', to='domain.projectworkspace'),
        ),
    ]
