# Generated by Django 5.2.17 on 2026-08-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_append_only_provenance_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='allow_nonempty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrun',
            name='correction_lineage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importrun',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importrun',
            name='intended_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrun',
            name='selected_source_column',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importrun',
            name='source_identity_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrun',
            name='target_assessment_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='import_runs', to='domain.assessmentset'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='target_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='import_runs', to='domain.experiment'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_assessment_set__isnull', True), ('target_experiment__isnull', True)), models.Q(('target_assessment_set__isnull', False), ('target_experiment__isnull', False)), _connector='OR'), name='domain_import_target_lane_pair'),
        ),
    ]
