# Generated by Django 5.2.17 on 2026-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_import_receipt_contract'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatcitation',
            name='domain_chat_citation_exact_span',
        ),
        migrations.AddConstraint(
            model_name='chatcitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_version__isnull', True), ('fact__isnull', False), ('fragment__isnull', True), ('quote_end__isnull', True), ('quote_start__isnull', True), ('quote_text', '')), models.Q(('document_version__isnull', False), ('fragment__isnull', False), ('quote_end__isnull', False), ('quote_start__isnull', False), models.Q(('quote_text', ''), _negated=True), ('quote_end__gt', models.F('quote_start'))), _connector='OR'), name='domain_chat_citation_target_state'),
        ),
    ]
