# Generated by Django 5.2.17 on 2026-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_chat_citation_target_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfragment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timeslice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
