# Generated by Django 5.2.17 on 2026-09-04 11:23

import hashlib

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_legacy_multilingual_evidence(apps, schema_editor):
    """Add only mechanical legacy pins; never fabricate linguistic meaning."""

    database = schema_editor.connection.alias
    Document = apps.get_model("domain", "Document")
    DocumentContent = apps.get_model("domain", "DocumentContent")
    DocumentContentVariant = apps.get_model("domain", "DocumentContentVariant")
    TextFragment = apps.get_model("domain", "TextFragment")

    Document.objects.using(database).update(
        root_document=models.F("pk"),
        predecessor_document=None,
        lineage_kind="LEGACY_CAPTURE",
        translation_synchronized=False,
    )

    version_to_variant: dict[object, object] = {}
    contents = DocumentContent.objects.using(database).all().iterator()
    for content in contents:
        text = content.normalized_text or ""
        if not text and content.original_bytes is not None:
            try:
                text = bytes(content.original_bytes).decode(
                    content.encoding or "utf-8", errors="replace"
                )
            except LookupError:
                text = bytes(content.original_bytes).decode("utf-8", errors="replace")
        # DocumentContent is still the byte/hash authority.  This secondary
        # normalized-text checksum only fixes the variant coordinate system.
        variant, _created = DocumentContentVariant.objects.using(database).get_or_create(
            document_content_id=content.pk,
            defaults={
                "workspace_id": content.workspace_id,
                "document_version_id": content.document_version_id,
                "code": f"LEGACY-VARIANT-{content.pk.hex}",
                "version": content.version,
                "variant_kind": "LEGACY_UNSPECIFIED",
                "language_tag": "und",
                "normalized_text": text,
                "content_sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "segmentation_version": "legacy-capture-v1",
                "normalization_version": content.normalization_version
                or "legacy-capture-v1",
                "metadata": {"legacy_capture_sha256": content.content_sha256},
            },
        )
        version_to_variant[content.document_version_id] = variant.pk

    for fragment in TextFragment.objects.using(database).filter(
        anchor_status="EXACT"
    ).iterator():
        variant_id = version_to_variant.get(fragment.document_version_id)
        if variant_id is not None:
            TextFragment.objects.using(database).filter(pk=fragment.pk).update(
                content_variant_id=variant_id
            )


def reverse_legacy_multilingual_evidence(apps, schema_editor):
    """Clear successor pointers before Django drops their additive schema."""

    database = schema_editor.connection.alias
    Document = apps.get_model("domain", "Document")
    TextFragment = apps.get_model("domain", "TextFragment")
    TextFragment.objects.using(database).update(content_variant=None)
    Document.objects.using(database).update(
        root_document=None,
        predecessor_document=None,
        lineage_kind="LEGACY_CAPTURE",
        translation_synchronized=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_project_primary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lineage_kind',
            field=models.CharField(choices=[('LEGACY_CAPTURE', 'Legacy capture'), ('INITIAL_INGEST', 'Initial multilingual ingest'), ('TRANSLATION_EDIT', 'Translation edit derivative'), ('REALIGNMENT', 'Explicit realignment derivative')], default='LEGACY_CAPTURE', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='predecessor_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lineage_successors', to='domain.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='root_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lineage_descendants', to='domain.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='translation_synchronized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentContentVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_kind', models.CharField(choices=[('LEGACY_UNSPECIFIED', 'Legacy unspecified'), ('DECLARED', 'Declared capture variant'), ('TRANSLATED', 'Translated variant')], max_length=32)),
                ('language_tag', models.CharField(max_length=255)),
                ('normalized_text', models.TextField()),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='A manifest hash must be a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('segmentation_version', models.CharField(max_length=64)),
                ('normalization_version', models.CharField(default='multilingual-v1', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='multilingual_variants', to='domain.documentcontent')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='content_variants', to='domain.documentversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_content_variants', to='domain.projectworkspace')),
            ],
            options={
                'ordering': ('workspace__code', 'document_version__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DocumentContentRoleBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ORIGINAL', 'Original'), ('PROJECT_PRIMARY', 'Project primary')], max_length=32)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='content_role_bindings', to='domain.documentversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_content_role_bindings', to='domain.projectworkspace')),
                ('content_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='role_bindings', to='domain.documentcontentvariant')),
            ],
            options={
                'ordering': ('workspace__code', 'document_version__code', 'role'),
            },
        ),
        migrations.AddField(
            model_name='textfragment',
            name='content_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fragments', to='domain.documentcontentvariant'),
        ),
        migrations.CreateModel(
            name='DocumentSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('text_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='A manifest hash must be a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('segmentation_version', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sentences', to='domain.documentcontentvariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_sentences', to='domain.projectworkspace')),
            ],
            options={
                'ordering': ('workspace__code', 'content_variant__code', 'sentence_number'),
            },
        ),
        migrations.CreateModel(
            name='FactCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='domain.factcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fact_categories', to='domain.project')),
            ],
            options={
                'ordering': ('project__code', 'code', 'version'),
            },
        ),
        migrations.CreateModel(
            name='FactCategoryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification_status', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('UNKNOWN', 'Unknown'), ('PROVISIONAL', 'Provisional'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Disputed')], default='UNCLASSIFIED', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='domain.factcategory')),
                ('fact', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='category_assignment', to='domain.fact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fact_category_assignments', to='domain.projectworkspace')),
            ],
            options={
                'ordering': ('workspace__code', 'fact__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='SentenceAlignmentSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_segmentation_version', models.CharField(max_length=64)),
                ('project_primary_segmentation_version', models.CharField(max_length=64)),
                ('alignment_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='A manifest hash must be a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sentence_alignment_sets', to='domain.documentversion')),
                ('original_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original_alignment_sets', to='domain.documentcontentvariant')),
                ('project_primary_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='primary_alignment_sets', to='domain.documentcontentvariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sentence_alignment_sets', to='domain.projectworkspace')),
            ],
            options={
                'ordering': ('workspace__code', 'document_version__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='SentenceAlignmentEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardinality', models.CharField(choices=[('ONE_TO_ONE', '1:1'), ('ONE_TO_MANY', '1:N'), ('MANY_TO_ONE', 'N:1')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('original_sentence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original_alignment_edges', to='domain.documentsentence')),
                ('project_primary_sentence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='primary_alignment_edges', to='domain.documentsentence')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sentence_alignment_edges', to='domain.projectworkspace')),
                ('alignment_set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='edges', to='domain.sentencealignmentset')),
            ],
            options={
                'ordering': ('workspace__code', 'alignment_set__code', 'original_sentence__sentence_number', 'project_primary_sentence__sentence_number'),
            },
        ),
        migrations.CreateModel(
            name='TranslationProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_language_tag', models.CharField(max_length=255)),
                ('target_language_tag', models.CharField(max_length=255)),
                ('translation_id', models.CharField(max_length=128)),
                ('translation_version', models.CharField(max_length=64)),
                ('translated_at', models.DateTimeField()),
                ('actor_type', models.CharField(choices=[('HUMAN', 'Human'), ('AI', 'AI'), ('HYBRID', 'Hybrid'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('actor_identifier', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('method_version', models.CharField(blank=True, max_length=255)),
                ('knowledge', models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('alignment_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translation_provenance_rows', to='domain.sentencealignmentset')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translation_provenance_rows', to='domain.documentversion')),
                ('project_primary_variant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='translation_provenance', to='domain.documentcontentvariant')),
                ('source_content_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translation_sources', to='domain.documentcontentvariant')),
                ('source_document_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translation_derivatives', to='domain.documentversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translation_provenance_rows', to='domain.projectworkspace')),
            ],
            options={
                'ordering': ('workspace__code', 'document_version__code', 'code'),
            },
        ),
        # All successor tables and nullable pins now exist.  Backfill only
        # mechanical legacy capture identities before enforcing final checks.
        migrations.RunPython(
            backfill_legacy_multilingual_evidence,
            reverse_legacy_multilingual_evidence,
        ),
        migrations.AddConstraint(
            model_name='documentcontentvariant',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_doc_variant_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentvariant',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_doc_variant_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentvariant',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_doc_variant_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentvariant',
            constraint=models.CheckConstraint(condition=models.Q(('variant_kind', 'LEGACY_UNSPECIFIED'), models.Q(('normalized_text', ''), _negated=True), _connector='OR'), name='domain_doc_variant_text_present'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentrolebinding',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_doc_role_binding_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentrolebinding',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_doc_role_binding_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentrolebinding',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_doc_role_binding_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentcontentrolebinding',
            constraint=models.UniqueConstraint(fields=('document_version', 'role'), name='domain_doc_role_binding_role_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentsentence',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_doc_sentence_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='documentsentence',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_doc_sentence_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='documentsentence',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_doc_sentence_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentsentence',
            constraint=models.UniqueConstraint(fields=('content_variant', 'sentence_number'), name='domain_doc_sentence_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentsentence',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('start_offset'))), name='domain_doc_sentence_offsets_ordered'),
        ),
        migrations.AddConstraint(
            model_name='documentsentence',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='domain_doc_sentence_text_present'),
        ),
        migrations.AddConstraint(
            model_name='factcategory',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_fact_category_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='factcategory',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_fact_category_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='factcategory',
            constraint=models.UniqueConstraint(fields=('project', 'code', 'version'), name='domain_fact_category_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='factcategory',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='domain_fact_category_name_present'),
        ),
        migrations.AddConstraint(
            model_name='factcategoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_fact_category_assignment_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='factcategoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_fact_category_assignment_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='factcategoryassignment',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_fact_category_assignment_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='factcategoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('classification_status', 'UNCLASSIFIED')), ('category__isnull', False), _connector='OR'), name='domain_fact_category_assignment_state'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentset',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_alignment_set_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentset',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_alignment_set_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentset',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_alignment_set_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentset',
            constraint=models.UniqueConstraint(fields=('document_version',), name='domain_alignment_set_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentedge',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_alignment_edge_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentedge',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_alignment_edge_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentedge',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_alignment_edge_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sentencealignmentedge',
            constraint=models.UniqueConstraint(fields=('alignment_set', 'original_sentence', 'project_primary_sentence'), name='domain_alignment_edge_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='translationprovenance',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='domain_translation_provenance_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='translationprovenance',
            constraint=models.CheckConstraint(condition=models.Q(('version', ''), _negated=True), name='domain_translation_provenance_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='translationprovenance',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='domain_translation_provenance_ws_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='translationprovenance',
            constraint=models.CheckConstraint(condition=models.Q(('knowledge', 'KNOWN'), models.Q(('knowledge', 'UNKNOWN'), ('method_version', ''), ('model', ''), ('provider', '')), _connector='OR'), name='domain_translation_provenance_known_boundary'),
        ),
    ]
