# Generated by Django 5.2.17 on 2026-09-16 17:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def geography_guards(apps, schema_editor):
    """Append-only even through raw SQL; FK identities cannot cross projects."""
    del apps
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "sqlite":
            for table in ("geographicarea", "projectlocationrevision"):
                for operation in ("UPDATE", "DELETE"):
                    cursor.execute(f"CREATE TRIGGER geo_{table}_{operation.lower()} BEFORE {operation} ON domain_{table} BEGIN SELECT RAISE(ABORT, 'GEOGRAPHY_IMMUTABLE'); END")
            checks = {
                "area_parent": ("geographicarea", "INSERT", "NEW.parent_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM domain_geographicarea p WHERE p.id=NEW.parent_id AND p.dataset_code=NEW.dataset_code AND p.dataset_version=NEW.dataset_version AND p.id<>NEW.id)"),
                "revision_parent": ("projectlocationrevision", "INSERT", "NEW.supersedes_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision p WHERE p.id=NEW.supersedes_id AND p.project_id=NEW.project_id)"),
                "revision_area": ("projectlocationrevision", "INSERT", "NEW.area_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM domain_geographicarea a WHERE a.id=NEW.area_id AND a.dataset_code=NEW.boundary_dataset_code AND a.dataset_version=NEW.boundary_dataset_version AND a.boundary_policy_version=NEW.boundary_policy_version)"),
                "head_insert": ("projectlocationhead", "INSERT", "NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision r WHERE r.id=NEW.revision_id AND r.project_id=NEW.project_id AND r.supersedes_id IS NULL)"),
                "head_update": ("projectlocationhead", "UPDATE", "NEW.project_id<>OLD.project_id OR NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision r WHERE r.id=NEW.revision_id AND r.project_id=NEW.project_id AND r.supersedes_id=OLD.revision_id)"),
            }
            for name, (table, operation, condition) in checks.items():
                cursor.execute(f"CREATE TRIGGER geo_{name} BEFORE {operation} ON domain_{table} WHEN {condition} BEGIN SELECT RAISE(ABORT, 'GEOGRAPHY_INTEGRITY'); END")
            cursor.execute("CREATE TRIGGER geo_head_delete BEFORE DELETE ON domain_projectlocationhead BEGIN SELECT RAISE(ABORT, 'GEOGRAPHY_HEAD_DELETE'); END")
        elif vendor == "postgresql":
            cursor.execute("""
                CREATE FUNCTION geography_immutable() RETURNS trigger AS $$
                BEGIN RAISE EXCEPTION 'GEOGRAPHY_IMMUTABLE'; END; $$ LANGUAGE plpgsql;
                CREATE FUNCTION geography_area_insert() RETURNS trigger AS $$
                BEGIN
                  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM domain_geographicarea p WHERE p.id=NEW.parent_id AND p.dataset_code=NEW.dataset_code AND p.dataset_version=NEW.dataset_version AND p.id<>NEW.id) THEN RAISE EXCEPTION 'GEOGRAPHY_INTEGRITY'; END IF;
                  RETURN NEW;
                END; $$ LANGUAGE plpgsql;
                CREATE FUNCTION geography_revision_insert() RETURNS trigger AS $$
                BEGIN
                  IF NEW.supersedes_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision p WHERE p.id=NEW.supersedes_id AND p.project_id=NEW.project_id) THEN RAISE EXCEPTION 'GEOGRAPHY_INTEGRITY'; END IF;
                  IF NEW.area_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM domain_geographicarea a WHERE a.id=NEW.area_id AND a.dataset_code=NEW.boundary_dataset_code AND a.dataset_version=NEW.boundary_dataset_version AND a.boundary_policy_version=NEW.boundary_policy_version) THEN RAISE EXCEPTION 'GEOGRAPHY_INTEGRITY'; END IF;
                  RETURN NEW;
                END; $$ LANGUAGE plpgsql;
                CREATE FUNCTION geography_head_write() RETURNS trigger AS $$
                BEGIN
                  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'GEOGRAPHY_HEAD_DELETE'; END IF;
                  IF NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision r WHERE r.id=NEW.revision_id AND r.project_id=NEW.project_id) THEN RAISE EXCEPTION 'GEOGRAPHY_INTEGRITY'; END IF;
                  IF TG_OP='UPDATE' THEN
                    IF NEW.project_id<>OLD.project_id OR NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision r WHERE r.id=NEW.revision_id AND r.supersedes_id=OLD.revision_id) THEN RAISE EXCEPTION 'GEOGRAPHY_INTEGRITY'; END IF;
                  ELSE
                    IF NOT EXISTS (SELECT 1 FROM domain_projectlocationrevision r WHERE r.id=NEW.revision_id AND r.supersedes_id IS NULL) THEN RAISE EXCEPTION 'GEOGRAPHY_INTEGRITY'; END IF;
                  END IF;
                  RETURN NEW;
                END; $$ LANGUAGE plpgsql;
            """)
            for table in ("geographicarea", "projectlocationrevision"):
                cursor.execute(f"CREATE TRIGGER geo_{table}_immutable BEFORE UPDATE OR DELETE ON domain_{table} FOR EACH ROW EXECUTE FUNCTION geography_immutable()")
            for table, func in (("geographicarea", "area_insert"), ("projectlocationrevision", "revision_insert")):
                cursor.execute(f"CREATE TRIGGER geo_{table}_insert BEFORE INSERT ON domain_{table} FOR EACH ROW EXECUTE FUNCTION geography_{func}()")
            cursor.execute("CREATE TRIGGER geo_head_write BEFORE INSERT OR UPDATE OR DELETE ON domain_projectlocationhead FOR EACH ROW EXECUTE FUNCTION geography_head_write()")
        else:
            raise RuntimeError("Geography requires PostgreSQL or SQLite")


def reverse_guards(apps, schema_editor):
    # Never silently discard accepted history. A populated deployment rolls
    # back application code while retaining 0019; restoration uses a backup.
    for name in ("ProjectLocationRevision", "GeographicArea", "ProjectLocationHead"):
        if apps.get_model("domain", name).objects.using(schema_editor.connection.alias).exists():
            raise RuntimeError("GEOGRAPHY_ROLLBACK_REQUIRES_EMPTY_TABLES")
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            for name in ("immutable", "area_insert", "revision_insert", "head_write"):
                cursor.execute(f"DROP FUNCTION geography_{name}() CASCADE")
    elif schema_editor.connection.vendor == "sqlite":
        # Reverse AddConstraint rebuilds tables before DeleteModel. Remove
        # cross-table triggers first, or SQLite rejects the temporary missing
        # revision table while renaming the rebuilt table.
        names = [f"geo_{table}_{operation}" for table in ("geographicarea", "projectlocationrevision") for operation in ("update", "delete")]
        names += ["geo_area_parent", "geo_revision_parent", "geo_revision_area", "geo_head_insert", "geo_head_update", "geo_head_delete"]
        with schema_editor.connection.cursor() as cursor:
            for name in names:
                cursor.execute(f'DROP TRIGGER IF EXISTS "{name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0018_workspace_assessment_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_code', models.CharField(max_length=80)),
                ('dataset_version', models.CharField(max_length=64)),
                ('feature_id', models.CharField(max_length=128)),
                ('area_level', models.CharField(choices=[('ADM0', 'ADM0'), ('ADM1', 'ADM1')], max_length=16)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_local', models.CharField(blank=True, max_length=255)),
                ('iso_alpha2', models.CharField(max_length=2)),
                ('boundary_policy_version', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='domain.geographicarea')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ProjectLocationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Codes must start with an ASCII letter or digit and contain only letters, digits, dot, underscore, colon, or hyphen.', regex='^[A-Za-z0-9][A-Za-z0-9_.:-]*$')])),
                ('version', models.CharField(default='1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_kind', models.CharField(choices=[('POINT', 'Примерная точка'), ('AREA', 'Территория'), ('REGION', 'Регион'), ('COUNTRY', 'Государство'), ('TRANSBOUNDARY', 'Трансграничная')], max_length=16)),
                ('uncertainty_radius_m', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('source_kind', models.CharField(choices=[('USER_MAP', 'Указано на карте'), ('MANUAL_COORDINATES', 'Введено вручную'), ('DOCUMENT', 'Документ'), ('IMPORT', 'Импорт'), ('SYSTEM', 'Система')], max_length=24)),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('rationale', models.TextField()),
                ('actor_identifier', models.CharField(max_length=255)),
                ('operation_id', models.UUIDField(unique=True)),
                ('request_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='A manifest hash must be a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('boundary_dataset_code', models.CharField(max_length=80)),
                ('boundary_dataset_version', models.CharField(max_length=64)),
                ('boundary_policy_version', models.CharField(max_length=64)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='domain.geographicarea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='location_revisions', to='domain.project')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='successor', to='domain.projectlocationrevision')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ProjectLocationHead',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='location_head', serialize=False, to='domain.project')),
                ('etag_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='A manifest hash must be a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='domain.projectlocationrevision')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='geographicarea',
            constraint=models.UniqueConstraint(fields=('dataset_code', 'dataset_version', 'feature_id'), name='geo_area_dataset_feature_uniq'),
        ),
        migrations.AddConstraint(
            model_name='geographicarea',
            constraint=models.CheckConstraint(condition=models.Q(('name_ru', ''), _negated=True), name='geo_area_ru_required'),
        ),
        migrations.AddConstraint(
            model_name='geographicarea',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='geo_area_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='projectlocationrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', True)), fields=('project',), name='geo_revision_one_root'),
        ),
        migrations.AddConstraint(
            model_name='projectlocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='geo_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='projectlocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='geo_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='projectlocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('uncertainty_radius_m__isnull', True), models.Q(('uncertainty_radius_m__gte', 0), ('uncertainty_radius_m__lte', 20000000)), _connector='OR'), name='geo_radius_range'),
        ),
        migrations.AddConstraint(
            model_name='projectlocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('location_kind', 'POINT'), models.Q(('location_kind__in', ('AREA', 'REGION', 'COUNTRY', 'TRANSBOUNDARY')), ('uncertainty_radius_m__gt', 0), ('uncertainty_radius_m__isnull', False)), _connector='OR'), name='geo_extent_requires_radius'),
        ),
        migrations.AddConstraint(
            model_name='projectlocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rationale', ''), _negated=True), models.Q(('actor_identifier', ''), _negated=True)), name='geo_attribution_required'),
        ),
        migrations.RunPython(geography_guards, reverse_guards),
    ]
